name: Linux Tests

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/linux-tests.yml'
      - '**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/linux-tests.yml'
      - '**/*.swift'
    
jobs:
  test:
    name: Linux Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: [ "5.2.5", "5.3", "5.3.1", "5.3.2", "5.3.3", "5.4.1", "5.4.2" ]
        os: [ amazonlinux2, bionic, centos7, centos8, focal, xenial ]
    
    container:
      image: swift:${{ matrix.swift }}-${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery
