name: Linux Tests

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/linux-tests.yml'
      - '**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/linux-tests.yml'
      - '**/*.swift'
    
jobs:

  # Swift 5.3.1

  test-5_3_1-amazon-linux:
    name: Linux Tests - Swift 5.3.1 - Amazon Linux 2
    runs-on: ubuntu-latest

    container:
      image: swift:5.3.1-amazonlinux2

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_3_1-bionic:
    name: Linux Tests - Swift 5.3.1 - Ubuntu 18.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.3.1-bionic

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_3_1-centos7:
    name: Linux Tests - Swift 5.3.1 - CentOS 7
    runs-on: ubuntu-latest

    container:
      image: swift:5.3.1-centos7

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_3_1-centos8:
    name: Linux Tests - Swift 5.3.1 - CentOS 8
    runs-on: ubuntu-latest

    container:
      image: swift:5.3.1-centos8

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_3_1-focal:
    name: Linux Tests - Swift 5.3.1 - Ubuntu 20.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.3.1-focal

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_3_1-xenial:
    name: Linux Tests - Swift 5.3.1 - Ubuntu 16.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.3.1-xenial

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  # Swift 5.3

  test-5_3-amazon-linux:
    name: Linux Tests - Swift 5.3 - Amazon Linux 2
    runs-on: ubuntu-latest

    container:
      image: swift:5.3-amazonlinux2

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_3-bionic:
    name: Linux Tests - Swift 5.3 - Ubuntu 18.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.3-bionic

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_3-centos7:
    name: Linux Tests - Swift 5.3 - CentOS 7
    runs-on: ubuntu-latest

    container:
      image: swift:5.3-centos7

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_3-centos8:
    name: Linux Tests - Swift 5.3 - CentOS 8
    runs-on: ubuntu-latest

    container:
      image: swift:5.3-centos8

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_3-focal:
    name: Linux Tests - Swift 5.3 - Ubuntu 20.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.3-focal

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_3-xenial:
    name: Linux Tests - Swift 5.3 - Ubuntu 16.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.3-xenial

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  # Swift 5.2

  test-5_2-amazon-linux:
    name: Linux Tests - Swift 5.2 - Amazon Linux 2
    runs-on: ubuntu-latest

    container:
      image: swift:5.2.5-amazonlinux2

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_2-bionic:
    name: Linux Tests - Swift 5.2 - Ubuntu 18.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.2.5-bionic

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_2-centos7:
    name: Linux Tests - Swift 5.2 - CentOS 7
    runs-on: ubuntu-latest

    container:
      image: swift:5.2.5-centos7

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_2-centos8:
    name: Linux Tests - Swift 5.2 - CentOS 8
    runs-on: ubuntu-latest

    container:
      image: swift:5.2.5-centos8

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_2-focal:
    name: Linux Tests - Swift 5.2 - Ubuntu 20.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.2.5-focal

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5_2-xenial:
    name: Linux Tests - Swift 5.2 - Ubuntu 16.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.2.5-xenial

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery
