name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/tests.yml'
      - '**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/tests.yml'
      - '**/*.swift'
    
jobs:

  # Swift 5.3

  test-5.3-amazon-linux:
    name: Linux Tests - Swift 5.3 - Amazon Linux 2
    runs-on: ubuntu-latest

    container:
      image: swift:5.3-amazonlinux2

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5.3-bionic:
    name: Linux Tests - Swift 5.3 - Ubuntu 18.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.3-bionic

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5.3-centos7:
    name: Linux Tests - Swift 5.3 - CentOS 7
    runs-on: ubuntu-latest

    container:
      image: swift:5.3-centos7

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5.3-centos8:
    name: Linux Tests - Swift 5.3 - CentOS 8
    runs-on: ubuntu-latest

    container:
      image: swift:5.3-centos8

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5.3-focal:
    name: Linux Tests - Swift 5.3 - Ubuntu 20.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.3-focal

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5.3-xenial:
    name: Linux Tests - Swift 5.3 - Ubuntu 16.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.3-xenial

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  # Swift 5.2

  test-5.2-amazon-linux:
    name: Linux Tests - Swift 5.2 - Amazon Linux 2
    runs-on: ubuntu-latest

    container:
      image: swift:5.2.5-amazonlinux2

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5.2-bionic:
    name: Linux Tests - Swift 5.2 - Ubuntu 18.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.2.5-bionic

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5.2-centos7:
    name: Linux Tests - Swift 5.2 - CentOS 7
    runs-on: ubuntu-latest

    container:
      image: swift:5.2.5-centos7

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5.2-centos8:
    name: Linux Tests - Swift 5.2 - CentOS 8
    runs-on: ubuntu-latest

    container:
      image: swift:5.2.5-centos8

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5.2-focal:
    name: Linux Tests - Swift 5.2 - Ubuntu 20.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.2.5-focal

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery

  test-5.2-xenial:
    name: Linux Tests - Swift 5.2 - Ubuntu 16.04
    runs-on: ubuntu-latest

    container:
      image: swift:5.2.5-xenial

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery
