name: macOS Tests

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/macos-tests.yml'
      - '**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/macos-tests.yml'
      - '**/*.swift'
    
jobs:
  test-macos-xcode-12_2:
    name: macOS Tests - Xcode 12.2
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: swift test
  
  test-macos-xcode-12:
    name: macOS Tests - Xcode 12
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: swift test

  test-macos-xcode-11:
    name: macOS Tests - Xcode 11
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: swift test
