name: SwiftLint

on:
  pull_request:
    branches: [ main ]

jobs:
  check-changes:
    name: Check for Changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - '.github/workflows/swiftlint.yml'
              - '.swiftlint.yml'
              - '**/*.swift'

  SwiftLint:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || needs.check-changes.outputs.changed == 'true' }}
    needs: check-changes
    steps:
      - uses: actions/checkout@v1
      - name: "🧹 SwiftLint changed files"
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict
        # env:
        #   DIFF_BASE: ${{ github.base_ref }}