name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/tests.yml'
      - '**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/tests.yml'
      - '**/*.swift'
    
jobs:
  test-macos:
    name: macOS
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: swift test
  
  test-ios:
    name: iOS
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: swift package generate-xcodeproj && xcrun xcodebuild test -scheme "Vexil-Package" -destination "platform=iOS Simulator,name=iPhone 8"

  test-tvos:
    name: tvOS
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: swift package generate-xcodeproj && xcrun xcodebuild test -scheme "Vexil-Package" -destination "platform=tvOS Simulator,name=Apple TV 4K"

  build-watchOS:
    name: watchOS (Build Only)
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: swift package generate-xcodeproj && xcrun xcodebuild build -scheme "Vexil-Package" -destination "generic/platform=watchos"

  test-linux:
    name: Linux
    runs-on: ubuntu-latest

    container:
      image: swift:5.2

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery