name: tvOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          changed:
            - '.github/workflows/tvos-tests.yml'
            - '**/*.swift'

  # build-tvos-beta:
  #   name: tvOS Tests - Xcode Betas
  #   runs-on: macos-11.0
  #   if: ${{ needs.check-changes.outputs.changed == 'true' }}
  #   strategy:
  #     matrix:
  #       xcode: [ "13.0" ]

  #   env:
  #     DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Build and Test
  #       run: swift package generate-xcodeproj && xcrun xcodebuild test -scheme "Vexil-Package" -destination "platform=tvOS Simulator,name=Apple TV 4K"

  build-tvos-macos-11:
    name: tvOS Tests - macOS 11
    runs-on: macos-11.0
    if: ${{ needs.check-changes.outputs.changed == 'true' }}
    strategy:
      matrix:
        xcode: [ "11.7", "12.4", "12.5.1", "13.0" ]

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: swift package generate-xcodeproj && xcrun xcodebuild test -scheme "Vexil-Package" -destination "platform=tvOS Simulator,name=Apple TV 4K"

  build-tvos-macos-10_15:
    name: tvOS Tests - macOS 10.15
    runs-on: macos-10.15
    if: ${{ needs.check-changes.outputs.changed == 'true' }}
    strategy:
      matrix:
        xcode: [ "11.7", "12", "12.1", "12.2", "12.3", "12.4" ]

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: swift package generate-xcodeproj && xcrun xcodebuild test -scheme "Vexil-Package" -destination "platform=tvOS Simulator,name=Apple TV 4K"
