name: watchOS Build Tests

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/watchos-tests.yml'
      - '**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/watchos-tests.yml'
      - '**/*.swift'
    
jobs:
  build-watchos-beta:
    name: watchOS Build - Xcode Betas
    runs-on: macos-11.0
    strategy:
      matrix:
        xcode: [ 13.0 ]

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: swift package generate-xcodeproj && xcrun xcodebuild build -scheme "Vexil-Package" -destination "generic/platform=watchos"

  build-watchos-macos-11:
    name: watchOS Build - macOS 11
    runs-on: macos-11.0
    strategy:
      matrix:
        xcode: [ 11.7, 12.2, 12.3, 12.4, 12.5 ]

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: swift package generate-xcodeproj && xcrun xcodebuild build -scheme "Vexil-Package" -destination "generic/platform=watchos"

  build-watchos-macos-10_15:
    name: watchOS Build - macOS 10.15
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [ 11.7, 12, 12.1, 12.2, 12.3, 12.4, 12.5 ]

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: swift package generate-xcodeproj && xcrun xcodebuild build -scheme "Vexil-Package" -destination "generic/platform=watchos"
